### ISSUE TITLE
When content height changes while open, the close animation begins from the wrong height

### ISSUE THREAD

**Issue by mjhoffm2** [nkbt/react-collapse#191]
When I open my collapse component, and then the inner contents change to a new height, it seems that the collapse animation will jump to the old height when it starts instead of animating from the current height.

I believe I traced this issue down to the fact that while idle, the react-motion component keeps getting passed the old height from the end of the opening animation, and once it gets a new spring and height: auto is removed, it will still be interpolating from the old height.  I think the solution is that the new beginning height needs to be passed to react-motion without the spring before the animation begins.

I think you can accomplish this by essentially chaining two animations together.  The first animation would just instantly set the height to the new content.clientHeight, then once that resolves (with onRest) you start the actual collapse animation.

**Comment by deshiknaves** [comment]
Yep, I'm seeing the exact same issue.

**Comment by deshiknaves** [comment]
If your fix is working, any chance that can be pulled in?

**Comment by mjhoffm2** [comment]
It works, but I ended up just doing a polling system that checks the content's height every 1 second and updates the state if necessary.  A proper fix probably work like I mentioned earlier with a two part animation.

**Comment by nkbt** [comment]
Yeah, that is a known issue and though proposed solution makes sense, I was
not able to get it reliably working for now :(

-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by gnapse** [comment]
I was trying to use react-collapse to make a demo of my react-treefold component animating the expand/collapse of tree nodes, and I noticed exactly this. When I was going to report it, I noticed this issue, which I think describes what I was noticing.

So just in case it helps, [here's the demo](https://codesandbox.io/s/r75m3lv5op) where the behavior reported here can be reproduced. Here are some steps to reproduce it in that demo:

1. Expand "North America"
2. Expand "USA"
3. Collapse "North America"

At this point is a bit subtle because the collapsible segment height of "North America" is larger than it was originally. I think it's more noticeable when the opposite occurs (i.e. the collapsible segment height is decreased while the segment is open). So continue with these other steps after the three ones above:

4. Expand "North America"
5. Collapse "USA"
6. Collapse "North America"

Here you can clearly notice that the height of "North America"'s child nodes segment briefly expands downwards to how large it was when "USA" was expanded, and then the animation to collapse "North America" starts from there.

**Comment by nkbt** [comment]
As new react-collapse@5.0.0 is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
