### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed React 16.9

### ISSUE THREAD

**Issue by AndyOGo** [nkbt/react-collapse#247]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Collapse

**Comment by nkbt** [comment]
https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js in master branch they do not exist anymore. You can install it as `@nkbt/react-collapse`

**Comment by AndyOGo** [comment]
@nkbt Thanks for your quick answer.
Did you move all your projects into your own npm org?
We still use the latest `react-collapse`

**Comment by nkbt** [comment]
It has somewhat different implementation. Mostly compatible, so my main projects were updated without any issues. But I do not have any proper docs and migration guides, so the new version is kind of stuck at that personal namespace. Though it is stable for last year and used in prod

**Comment by AndyOGo** [comment]
Alright, thank you for your quick help. I will give it a try

**Comment by nkbt** [comment]
I now use it with css transitions, much lighter. You can do react motion too, though I do not have an example of that.
I will find an example with css, hopefully can do it on the phone as I am travelling right now.

**Comment by nkbt** [comment]
https://github.com/nkbt/react-collapse/blob/master/example/App/VariableText.js

And css https://github.com/nkbt/react-collapse/blob/7c45abd747d18e53d3a5549d1d5ee230c190f33b/example/app.css#L51

You can also pass your own classnames to collapse as ‘theme’ object like

<Collapse isOpened={isOpened} theme={{collapse: css.collapse}}>

Also just check all the examples in repo they should all work

**Comment by patelmayankce** [comment]
Thanks, @nkbt for quick response, I will try with CSS.

**Comment by reintroducing** [comment]
@nkbt do you have any plans to update this package with the one in your personal namespace? Or otherwise switch the "official" support to the personal namespaced one? I had a TODO in my codebase to investigate alternatives to react-collapse because of the dependency on motion and the general bundle size impact of react-collapse because of it, but it looks like you've corrected that in the other version. I'm just hesitant to move to it since its not "officially supported" if that makes sense.

**Comment by nkbt** [comment]
Yeah, I guess it needs to be published properly asap

I need a migration guide... if you managed to migrate your components without any issues - then it is possible to do so. Would really appreciate if you could write that down (what you had to change).

And rest seems to be easily doable.

Thank you!

**Comment by reintroducing** [comment]
I have yet to make the changes, I'm working on trimming bundle size in other areas at the moment, but this module is on my list. Once I get to it, if you haven't yet, I can document what I had to change, if anything, to get it working properly. Don't hold your breath though, it's slow going on a lot of other stuff before I get to the low hanging fruit which I bucket this update into. :)

**Comment by nkbt** [comment]
Sure, my goal is the same, I'm currently slowly phasing out react-motion and cleaning up the bundle too. Let me see if I can prepare a proper release soon with proper docs and migration guide in place. There is nothing worse then seeing a major update without proper migration guide (i've gone through this process literally last week, while updating all the major deps and had few I needed to go into source code to see what's changed)

**Comment by reintroducing** [comment]
@nkbt So I got a chance today to try the master branch in my project and I was able to get `Collapse` working properly. I then tried to use `UnmountClosed` and I can't for the life of me get it unmounted when closed. I've put together a very minimal example in the attached zip. Just `npm install` and `npm start` and you'll see when you toggle that it does not get removed from the DOM. 

What's incredibly odd is that I duplicated most of this code in your examples folder and it was indeed working, but I literally cannot figure out why this doesn't. If you could take a look I'd really appreciate it. Don't worry about the animation, it has no bearing on this particular example, I just tried to strip this down to as small as possible.

[react-collapse-rsr.zip](https://github.com/nkbt/react-collapse/files/3660510/react-collapse-rsr.zip)

**Comment by nkbt** [comment]
Have you checked examples folder? I am using it pretty much exclusively and have no issues

**Comment by reintroducing** [comment]
yes, like i said above, i basically duplicated everything i saw in the examples. i even put my code into your examples and it seemed to work as expected, but i had to adjust imports and some other small random stuff. i don't really know what i'm asking you to do, i feel like i've just been staring at it for too long now and was hoping to get a second set of eyes on it to see if anything jumps out.

**Comment by nkbt** [comment]
Your build is broken, quite a few missing dependencies like eslint-loader, prettier plugin etc. But I still cannot make it work without warnings, so I gave up.
Also the build looks unfamiliar for me so I do not know how to add classed/styles to elements (global styles for example)

From the code I see the main thing that is missing - CSS transition. New collapse has no JS animations by itself, you need to define how you animate yourself.

You can use global classnames like 
```
.ReactCollapse--collapse {
  transition: height 500ms;
}
.ReactCollapse--content {
}
```
or pass `theme={{collapse: 'your collapse classname', content: 'your content classname'}}` to Collapse element.

**Comment by reintroducing** [comment]
The build is not broken, all of those dependencies come bundled with `@reintroducing/rsr` so they are not included in the dependencies list. That's basically my version of create-react-app. In regards to the transition or CSS, none of that is necessary for the purpose of this demo, I stripped it all out to get to as barebones as possible. I did the same thing to the examples in your code in an attempt to crack down on what was going on and its all unnecessary. The only thing to note here is the actual DOM itself, the fact that the `ReactCollapse--collapse` element remains in the DOM when the check is unchecked whereas it should not be there.

**Comment by nkbt** [comment]
fyi
![image](https://user-images.githubusercontent.com/175264/65737510-59df2280-e111-11e9-8d94-8ba6b32b939c.png)
![image](https://user-images.githubusercontent.com/175264/65737525-62375d80-e111-11e9-89c2-0d23418defe7.png)


Ah yeah... I see what you mean. Let me check more what is going on there. I haven't touched that code for over a year already...

**Comment by reintroducing** [comment]
Apologies about the build, not sure what is going on there, maybe i removed too much in my haste to make this easily digestible.

As for the code, what it looks like to me is that the getDerivedStateFromProps is running twice and overwriting the value for isResting to false. Its never true so the `Collapse` doesn't get removed.

**Comment by nkbt** [comment]
Ok, so the reason is - new React 16.9. My examples work perfectly fine with react 16.3.2. As soon as I've updated to the new react - state is batched and never gets into `isResting: true`, so collapse is not unmounted.

I haven't noticed that on my main projects as styles of collapsed content are no different from unmounted ones, so visually everything is perfect, except we have more dom elements. Thanks, will see if I can fix this.

**Comment by reintroducing** [comment]
Son of a b, I seriously thought i was going crazy, didn't even consider looking at the React versions. I'm glad you got that narrowed down, I guess this is why I shared the code after all, "a second set of eyes" :)

The good news is, updating from the prior version as we discussed above prior to the issues I had today was pretty easy and actually made my code much cleaner. What would it take to get this package out of alpha (after this issue is fixed) and into a proper release cycle/master?

**Comment by nkbt** [comment]
It's fixed now. Will publish new version soon. I should indeed do some documentation and finally release new version.

**Comment by reintroducing** [comment]
Awesome! The only thing that caught me up in the upgrade was making sure i added the transition to the CSS properly, otherwise it was pretty smooth sailing. I had to look over your example CSS to catch that, so I think if you just make sure thats part of the docs it should be relatively simple otherwise.

**Comment by nkbt** [comment]
Yeah, I’ve tried to maintain the same api, as I needed to upgrade my other projects too, so it was quite an easy path. There are only couple of props that re no longer supported as they are sort of meaningless in the new architecture.
I am upgrading all deps and build too, it’s been a while... hopefully get it all working plus docs soon

**Comment by nkbt** [comment]
It's been a long way to update all the deps... So finally the fix PR for UnmountClosed https://github.com/nkbt/react-collapse/pull/249

Docs update will come later as well as proper publish, still need to test things harder

**Comment by nkbt** [comment]
Published fix as https://github.com/nkbt/react-collapse/releases/tag/v5.0.0-alpha.3 I'm going to test it on some other projects and if everything is ok - will move it out of "alpha" stage.

UPD: tested and it works well so far. Need to check that standalone builds are all working as expected

**Comment by reintroducing** [comment]
Just tested it and it works perfectly. Thanks for getting this fixed so quickly, really appreciate it.

**Comment by ro-savage** [comment]
@nkbt - I tried upgrading to v5-alpha.3 from v4.

However, the animation no longer works. For both `UnmountClosed` and `Collapse`

Here is super simple example:
https://codesandbox.io/embed/async-breeze-o8mw8

I am not sure for if the API changed? I couldn't see anything on the docs about animation being off by default.

**Comment by ro-savage** [comment]
@nkbt - We have just tried it out. Got confused that we had to add the css transition. As I read rthe docs for v5 but I didnt look here.

Would it be possible to use inline styles to add the animation by default?

`styles={{ transition: "height 500ms" }}` but only add it if `theme.collapse` is missing?
Could also add a props `transitionSpeed` and `transitionType`.

`styles={{ transition: "height ${transitionSpeed || '500ms'} ${transitionType || 'linear'}" }}` 

Then your API change wouldn't be breaking.

**Comment by reintroducing** [comment]
I actually also wanted to control the animation speed with a prop but was unable to ultimately get that working. This would be a nice addition.

**Comment by nkbt** [comment]
Thanks @ro-savage for feedback. Since previously animation was controlled by react-motion, all the "speed" options were directly passed through to it and there is no real way to simulate them with css transitions (spring animation params). My goal also was not to lock into CSS transitions, but let you decide if you still want to keep react-motion (or any other animation library) as `react-collapse` only calculates and changes height of an element (0 -> XXpx -> auto) and it is up to consumer to define how exactly that transition is going to happen then. CSS seems to be the most obvious and easy solution though.

I'd rather keep it as simple and bare minimum as possible, as any extra prop makes it much more difficult to control if component needs updating and how it affects height and animation. Considering style is also calculated and used on Collapse element, any extra ones makes it harder to merge/validate/check etc.

**Comment by nkbt** [comment]
`react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0
