### ISSUE TITLE
Wrong height calculated in nested components

### ISSUE THREAD

**Issue by datoml** [nkbt/react-collapse#34]
Hello.
I found a strange behavior with react collapse when you dont wrap the content inside a div with padding > 0.

The problem appears inside my sidebar menu.

I took the Nested.js from the examples and modified it. So it should be easy to reproduce it.

This code works:
```
        <Collapse
          style={style.container}
          isOpened={isOpened}
          keepCollapsedContent={keepContent}>
            <div style={{padding: 1}}>
              <ul>
                <li>Hallo
                  <ul>
                    <li>
                      <VariableHeight />
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
        </Collapse>
```

This one calculates the height wrong and jumps the the right size after animation is finished.
```
        <Collapse
          style={style.container}
          isOpened={isOpened}
          keepCollapsedContent={keepContent}>            
              <ul>
                <li>Hallo
                  <ul>
                    <li>
                      <VariableHeight />
                    </li>
                  </ul>
                </li>
              </ul>            
        </Collapse>
```

Here's how it looks.
![react_collapse_jumping](https://cloud.githubusercontent.com/assets/10552487/12845316/44a8a294-cc05-11e5-8c2a-53d607d10b09.gif)

Thank you in advance. :)

**Comment by nkbt** [comment]
Ul/LI have some padding/margins by default (as you can easily check in dev tools). If you don't reset them to 0 or don't use proper wrapper (block element, without padding/margins) - behaviour may not be as expected.

Margins are the most trickiest ones. Better compensate them with paddings of collapsible container

**Comment by datoml** [comment]
Hmm.
I tried to set margin and padding to 0 and it works now.
But when I nest them multiple times I have the same effect like in the video.

**Comment by nkbt** [comment]
Could you please create a Codepen to try it out? Thanks!

**Comment by datoml** [comment]
Hey :).
Here's the codepen example.
[https://codepen.io/anon/pen/MKPENE?editors=0110](url)

Steps to reproduce:
* Fast uncheck and check the first one.
* After severel times you fast uncheck and chek the first one it starts working
* Uncheck the second one
* Uncheck the first one
* Check the fist one
* Fast uncheck and check the first one again

Hope it works :).

**Comment by nkbt** [comment]
Need to doublecheck if height is re-measured after `height: auto`, so nested elements can fix themselves in case of quick open/close actions.

**Comment by nkbt** [comment]
I really need https://github.com/chenglou/react-motion/pull/273 to be published, that would allow me to fix this issue quite effectively.

**Comment by Justkant** [comment]
Yeah really waiting for this to be fix.
Nice work on this lib

**Comment by benzen** [comment]
Heads up:
https://github.com/chenglou/react-motion/blob/master/src/Motion.js#L29
Seams like this was merged to master.
Still not released

**Comment by nkbt** [comment]
It is actually released as far as I know.

**Comment by benzen** [comment]
Weird since this was merged on 29 of january an the is only on gh release which was made on the 30.
But the release does not mention it.

Anyway, @nkbt do you have time to work on this ?

**Comment by nkbt** [comment]
I do and I will when I am back from holidays :)

No worries.

**Comment by davidspiess** [comment]
Any news here? :)

**Comment by nkbt** [comment]
oh jeez that was hell of a holiday I reckon... Thanks for ping @davidspiess

**Comment by nkbt** [comment]
Most likely to be fixed by #72

**Comment by nkbt** [comment]
Just published `react-collapse@next` (not `latest` channel yet until better tested) with full rewrite, which fixes this issue. Give it a shot if you are keen.

**Comment by sassanh** [comment]
@nkbt thanks for this great module, I found the nested behavior is not still buggy if you use more than one `<Collapse>` tag in a single render. It works alright if you use only one `<Collapse>` per component and nest them but if you use more than one `<Collapse>` in a single component it'll behave strange.
Look at this: https://codepen.io/sassanh/pen/GqLZVy?editors=0010

**Comment by nkbt** [comment]
Yeah I found issues with nested collapse too recently. Can be solved by
specifying if collapse has nested collapse elements (and then change
internal state transition logic), since it is tricky to catch that
automatically. It is not implemented yet, I will be able to get back to it
bit later.

PS: we are using collapse quite extensively in our work projects, so this
issue will be eventually solved :)


Thanks a lot for a Codepen, I will add it to examples when I have some
time. Feel free to add this example as PR if you are keen

**Comment by sassanh** [comment]
I'm glad to hear it'll be fixed. Meanwhile do you know any simple temporary workaround for this?

**Comment by sassanh** [comment]
Nvm, I was able to handle it with defining a `<DummyTag>` (which in contrast to its name is pretty complicated to be able to render child nodes considering requirements of my project.) and now it's working alright.

**Comment by nkbt** [comment]
the solution for now is to not pass any props through parent collapse if only children are changed (so children should be connected to a flux/redux store or something). Now when props of paren collapse are changed it is transitioned to state `WAITING`, which locks its `height`. Since it is own height is not changed after that (because children are expanded with animation, so the next step height is exactly as it was before) - it may forever stay in this state =(. 

So it works perfectly when children are expanded instantly (no nested collapse), but not working when collapse elements are nested.

I consider adding a flag `hasNestedCollapse` to skip this transition to `WAITING` state. This way everything would work perfectly since it has `height: auto`.

**Comment by nkbt** [comment]
@sassanh, I've opened #76 to track progress on this.
